# Profil Docker : base de donn√©es PostgreSQL via le service Docker
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/obi_v1?autoReconnect=true&useSSL=false
    username: postgres
    password: ${POSTGRES_PASSWORD:P@ssword123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
